version: '3'
services:
  spring-kotlin-exposed-local-db:
    image: local/spring-kotlin-exposed-db:latest
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=password"
    networks:
      - spring-kotlin-exposed-local-network
    volumes:
      - spring-kotlin-exposed-local-db-volume:/var/lib/postgresql/data

networks:
  spring-kotlin-exposed-local-network: {}
volumes:
  spring-kotlin-exposed-local-db-volume: {}
